# Generated by Django 5.2 on 2025-05-18 19:16

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_slug'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('custom', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
